# Introduction to Pandas

Pandas is a Python library used for data analysis and data manipulation.  
It provides powerful data structures like Series and DataFrame to work with structured data.

In [1]:
import pandas as pd

# Pandas Series

A Series is a one-dimensional labeled array capable of holding any data type.  
It is similar to a column in a table.

In [2]:
data = pd.Series([10,20,30,40])
print(data)

0    10
1    20
2    30
3    40
dtype: int64

# Creating a DataFrame

A DataFrame is a two-dimensional data structure that stores data in rows and columns.  
It is similar to a table in Excel or SQL.

In [3]:
data = {
 "Name": ["Ali","Sara","John"],
 "Age": [22,24,23],
 "City": ["Mumbai","Delhi","Pune"]
}

df = pd.DataFrame(data)
print(df)

   Name  Age    City
0   Ali   22  Mumbai
1  Sara   24   Delhi
2  John   23    Pune

# Viewing Data

Pandas provides functions to quickly view the dataset.  
These functions help understand the structure of the data.

In [4]:
df.head()
df.tail()

   Name  Age    City
0   Ali   22  Mumbai
1  Sara   24   Delhi
2  John   23    Pune

# DataFrame Information

The info() function shows details about the dataset such as column names, data types, and missing values.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 112.0+ bytes

# Shape of DataFrame

The shape attribute returns the number of rows and columns in the dataset.

In [6]:
df.shape

(3, 3)

# Selecting Columns

You can select a specific column from a DataFrame using its column name.

In [7]:
df["Name"]

0     Ali
1    Sara
2    John
Name: Name, dtype: object

In [8]:
df[["Name","Age"]]

   Name  Age
0   Ali   22
1  Sara   24
2  John   23

# Row Selection using loc

The loc function is used to select rows and columns by labels.

In [9]:
df.loc[0]

Name       Ali
Age         22
City    Mumbai
Name: 0, dtype: object

In [10]:
df.loc[1,"Name"]

'Sara'

# Row Selection using iloc

The iloc function is used to select rows and columns using index positions.

In [11]:
df.iloc[0]

Name       Ali
Age         22
City    Mumbai
Name: 0, dtype: object

In [12]:
df.iloc[1,0]

'Sara'

# Filtering Data

Filtering helps select rows based on specific conditions.

In [13]:
df[df["Age"] > 22]

   Name  Age   City
1  Sara   24  Delhi
2  John   23   Pune

# GroupBy Operation

GroupBy is used to group data based on a column and perform aggregation operations.

In [14]:
df.groupby("City")["Age"].mean()

City
Delhi     24
Mumbai    22
Pune      23
Name: Age, dtype: int64

# Handling Missing Values

Missing values are common in real-world datasets.  
Pandas provides functions to detect and handle missing data.

In [15]:
df.isnull()
df.fillna(0)
df.dropna()

   Name  Age    City
0   Ali   22  Mumbai
1  Sara   24   Delhi
2  John   23    Pune

# Statistical Functions

Pandas provides functions to calculate statistical measures like mean, sum, max, and min.

In [16]:
df["Age"].mean()
df["Age"].max()
df["Age"].min()

22